# Generated by Django 5.2.7 on 2025-10-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='map_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
